Optimized memchr implementation
foss-for-synopsys-dwc-arc-processors/newlib pull request #34
Opened 2022-10-12 16:02 UTC by BrunoASMauricio

Created assembly version of memchr with the objective of focusing on speed for larger amounts of memory/bigger memory regions.
Used measure of speed is instruction count via CPU counters.
Measurements against compiler generated code suggest a decrease in instruction count of ~40% for big memory sizes (200 bytes) and ~30% for smaller ones (14 bytes).
Newlib DejaGNU tests pass with success!

2022-10-19 09:17 UTC, BrunoASMauricio commented
Found a better way to perform the last 1 byte search. Will reopen when that is done

2023-01-25 13:46 UTC, claziss requested changes

2023-01-25 13:46 UTC, claziss commented on newlib/libc/machine/arc64/memchr.S
> +	or	r1, r1, r9
The above two instructions can be folded into `vpack2hl`

2023-01-25 13:46 UTC, claziss commented on newlib/libc/machine/arc64/memchr.S
> +	or	r1, r1, r9
Plz use `vpack2hl`

2023-02-09 14:10 UTC, claziss approved these changes

2023-02-09 14:41 UTC, merged